### ISSUE TITLE
Unexpected token error when running in node v4.2.6

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-playground/resin-toolbox#31]
hostOS: Linux betty 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
nodejs: v4.2.6
npm: 3.5.2
 

```
shaun$ resin-toolbox  ./bin/resin-toolbox                                                                                                                                        
/home/shaun/Desktop/resin-toolbox/node_modules/etcher-image-write/lib/validate.js:51
exports.usingBmap = (deviceFileDescriptor, options = {}) => {
                                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shaun/Desktop/resin-toolbox/node_modules/etcher-image-write/lib/index.js:26:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shaun/Desktop/resin-toolbox/build/actions/flash.js:35:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shaun/Desktop/resin-toolbox/build/actions/index.js:23:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shaun/Desktop/resin-toolbox/build/app.js:23:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shaun/Desktop/resin-toolbox/bin/resin-toolbox:2:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by lekkas** [comment]
The issue is that `etcher-image-write` was written directly in JS ES6  and uses language features like default parameters which are supported by default  in node  > 6 (https://github.com/nodejs/node/issues/3070#issuecomment-177447635)

So I guess we should just specify our requirements to node 6.x + ?

**Comment by shaunmulligan** [comment]
possibly setup an es6 to es5 transpiler in resin-toolbox as part of the coffee build rule?

**Comment by lekkas** [comment]
@shaunmulligan  @jviotti  started a thread in flowdock on this - in summary, it will probably make more sense to add traspiling in `etcher-image-write` and any other resin.io ES6 module, or any module/app that requires them will have to use a `babel-core/register()` `require()` hook to transpiled `require()`'d modules on-the-fly, which is terribly slow (app startup takes several seconds)
